export const api = "http://localhost:3000/api/products"
export const secret = "31387579c19deaf21d112a8fd2f050ef"
export const gitbook = "https://app.gitbook.com/o/JZY4lQs3jDfTFvrnCKnh/s/xzAkCqB4ZW2cEKD9uaMb/technologies/custom-app/get-started"
export const homemade = "https://raw.githubusercontent.com/iadvize/custom-app-demo/main/src/assets/forte.jpg"
export const watermelon = "https://raw.githubusercontent.com/iadvize/custom-app-demo/main/src/assets/watermelon.jpg"
export const pistachio = "https://raw.githubusercontent.com/iadvize/custom-app-demo/main/src/assets/pistachio.jpg"
export const gold = "https://raw.githubusercontent.com/iadvize/custom-app-demo/main/src/assets/gold%20exeprience.jpg"
export const mint = "https://raw.githubusercontent.com/iadvize/custom-app-demo/main/src/assets/mint.jpg"
